CREATE TABLE IF NOT EXISTS phones (
    id SERIAL PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    brand VARCHAR(100),
    model VARCHAR(100),
    price DOUBLE PRECISION,
    year INT,
    storage INT,
    battery_capacity INT,
    operating_system VARCHAR(50),
    weight DOUBLE PRECISION,
    color VARCHAR(50),
    camera_megapixels DOUBLE PRECISION,
    has_nfc BOOLEAN,
    satellite_network VARCHAR(100),
    antenna_length DOUBLE PRECISION,
    has_dual_sim BOOLEAN,
    has_flashlight BOOLEAN,
    secondary_screen_size DOUBLE PRECISION,
    fold_mechanism_type VARCHAR(100)
);
